### ISSUE TITLE
Minor issue about AStar

### ISSUE THREAD

**Issue by pkglimmer** [Meebuhs/maze-runner#7]
In InformedSolver.py, line 38:
```{python}
for cell in self.runner.get_neighbours(self.current_cell):
    if cell.parent is None:
        self.queue.put((self.calculate_cost(cell), cell))
        cell.parent = self.current_cell
        # Cost to cell is ignored by greedy search
        cell.cost = self.current_cell.cost + 1
        cell.in_queue = True
```

Before putting the new cell into queue, I think you should first update `cell.cost`, or else when `self.calculate_cost(cell)` is executed, the `cost` attribute would still be zero, which makes **AStar** behave exactly like **Greedy**. To fix this, just put `self.queue.put((self.calculate_cost(cell), cell))` to the end:

```{python}
for cell in self.runner.get_neighbours(self.current_cell):
    if cell.parent is None:
        cell.parent = self.current_cell
        # Cost to cell is ignored by greedy search
        cell.cost = self.current_cell.cost + 1
        cell.in_queue = True
        self.queue.put((self.calculate_cost(cell), cell))
```

**Comment by Meebuhs** [comment]
Thanks @PG98 this is a good catch. 

It also lead to the discovery of a slight bug with `GreedySolver.calculate_cost()` which would cause situations where the goal cell was either above or left of the start cell to be handled incorrectly. Specifically the line `return self.runner.goal_cell.x - cell.x + self.runner.goal_cell.y - cell.y` 

These fixes have been included in d7c7ec87d52b9bee6185495a74b1d0b973ba7d7d.
